class Models:
	SUBJECT = 'subject'
	REL = 'rel'
	REL_SUBJECT = 'rel_subject'
	REL_REL = 'rel_rel'
	ACTION = 'action'
	SUBJECT_SUBJECT_ACTION = 'subject_subject_action'
	REL_SUBJECT_ACTION = 'rel_subject_action'
	REL_REL_ACTION = 'rel_rel_action'
	SS_LOCATION = 'ss_location'
	RS_LOCATION = 'rs_location'
	RR_LOCATION = 'rr_location'