"""empty message

Revision ID: 0a0bf059f762
Revises: 7334c0f041ac
Create Date: 2017-02-25 17:47:38.167508

"""

# revision identifiers, used by Alembic.
revision = '0a0bf059f762'
down_revision = '7334c0f041ac'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_integration', sa.Column('meta', postgresql.JSON(), nullable=True))
    op.add_column('user_integration', sa.Column('refresh_token', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_integration', 'refresh_token')
    op.drop_column('user_integration', 'meta')
    ### end Alembic commands ###
