"""empty message

Revision ID: 0b21938ae092
Revises: 00a6948057b9
Create Date: 2017-02-02 01:21:01.995836

"""

# revision identifiers, used by Alembic.
revision = '0b21938ae092'
down_revision = '00a6948057b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    ### end Alembic commands ###
