"""empty message

Revision ID: 885ec8d01cfc
Revises: 82edf10df5bc
Create Date: 2017-02-05 00:06:21.245761

"""

# revision identifiers, used by Alembic.
revision = '885ec8d01cfc'
down_revision = '82edf10df5bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration', sa.Column('slug', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration', 'slug')
    ### end Alembic commands ###
