"""empty message

Revision ID: 90c414da7d32
Revises: 0b21938ae092
Create Date: 2017-02-02 02:06:18.593246

"""

# revision identifiers, used by Alembic.
revision = '90c414da7d32'
down_revision = '0b21938ae092'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uid', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'uid')
    ### end Alembic commands ###
