"""empty message

Revision ID: 94538cbba222
Revises: 90c414da7d32
Create Date: 2017-02-03 14:25:16.386931

"""

# revision identifiers, used by Alembic.
revision = '94538cbba222'
down_revision = '90c414da7d32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_destroyed', sa.Boolean(), server_default='f', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_formula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_destroyed', sa.Boolean(), server_default='f', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_formula_formula_id'), 'user_formula', ['formula_id'], unique=False)
    op.create_index(op.f('ix_user_formula_user_id'), 'user_formula', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_formula_user_id'), table_name='user_formula')
    op.drop_index(op.f('ix_user_formula_formula_id'), table_name='user_formula')
    op.drop_table('user_formula')
    op.drop_table('formula')
    ### end Alembic commands ###
