"""empty message

Revision ID: b8b92c266e00
Revises: 885ec8d01cfc
Create Date: 2017-02-05 00:51:05.864561

"""

# revision identifiers, used by Alembic.
revision = 'b8b92c266e00'
down_revision = '885ec8d01cfc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('botname', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'botname')
    ### end Alembic commands ###
